# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:


- task: PowerShell@2
  displayName: Pipelineeee
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Priya"
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(12fc5b53-fff0-4fa8-a751-d9e2b017e1b1)'
    appType: 'webApp'
    WebAppName: 'praticee'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'